---
- name: Generate Markdown files per Device
  hosts: all
  gather_facts: true
  connection: network_cli
  
  tasks:

  - name: TEMPLATE OUT IOS DEVICE-FACTS WITH JINJA2
    template: src=devicefact_ios.j2 dest="devices/{{inventory_hostname}}.md"
    when: ansible_network_os == 'ios'

  - name: TEMPLATE OUT NX-OS DEVICE-FACTS WITH JINJA2
    template: src=devicefact_nxos.j2 dest="devices/{{inventory_hostname}}.md"
    when: ansible_network_os == 'nxos'

