---
- name: Generate Markdown files per Device
  hosts: all
  gather_facts: true
  connection: network_cli
  
  tasks:

  - name: TEMPLATE OUT DEVICE-FACTS WITH JINJA2
    template: src=jinja2/devicefact.j2 dest="devices/{{inventory_hostname}}.md"
